import { create } from 'zustand';
import { createStarterSummonInstances, tutorialDefinitions } from '@psyblr/game-content';
import { canDeploySummon, canPlaceCampSummon, countCampOccupancy, countIlluminatiOccupancy, getCampPlacementForSummon, isIlluminatiCell, isIlluminatiFull, moveCampSummon, recallBattlefieldPlacement } from '@psyblr/game-rules';
import type { BattleCell, BattlefieldPlacement, CampCell, CampPlacement, CombatEvent, CombatSnapshot, SummonInstance, TutorialAction } from '@psyblr/contracts';
import { isTutorialActionAllowed, type TutorialContext } from '@psyblr/tutorial-core';
import { sameBattleCell } from '../game/battlefield';
import type { CameraPresetId } from '../game/camera';
import { emitGameInteraction } from '../game/interactionEvents';

export type SceneId = 'campaign' | 'base' | 'raid';
export type PerformanceSnapshot = { fps: number; frameTimeMs: number };
export type PlacementMode = 'idle' | 'selected' | 'dragging';
export type BattlePhase = 'setup' | 'running' | 'victory' | 'defeat' | 'draw';
export type BattleUnitView = { id: string; hp: number; maxHp: number; x: number; z: number; dead: boolean; shield: number };

type GameState = {
  scene: SceneId; debugOpen: boolean; autoCast: boolean; battlePhase: BattlePhase; battleSnapshot: CombatSnapshot | null; battleEvents: CombatEvent[]; battleTick: number; readySkillActorIds: string[]; deadUnitIds: string[]; battleUnits: Record<string, BattleUnitView>;
  inventory: SummonInstance[]; placements: BattlefieldPlacement[]; campPlacements: CampPlacement[];
  selectedSummonInstanceId: string | null; selectedCampSummonInstanceId: string | null; summonTrayOpen: boolean; summonDetailsOpen: boolean; placementMode: PlacementMode; campInteractionMode: PlacementMode; hoveredBattleCell: BattleCell | null; hoveredCampCell: CampCell | null;
  tutorialStepId: string | null; tutorialCompletedStepIds: string[]; tutorialContext: TutorialContext; boardOccupancy: number; boardCapacity: number; balls: number; ballCapacity: number; simulationSeed: string; performance: PerformanceSnapshot; cameraPresetId: CameraPresetId; cameraTransitioning: boolean;
  setScene: (scene: SceneId) => void; setSceneInternal: (scene: SceneId) => void; setCameraPreset: (preset: CameraPresetId, transitioning?: boolean) => void; setCameraTransitioning: (transitioning: boolean) => void; toggleDebug: () => void; setAutoCast: (autoCast: boolean) => void;
  beginBattle: (snapshot: CombatSnapshot, events: CombatEvent[], units: Record<string, BattleUnitView>) => void; updateBattle: (tick: number, events: CombatEvent[], units: Record<string, BattleUnitView>, readySkillActorIds: string[], deadUnitIds: string[]) => void; finishBattle: (phase: Exclude<BattlePhase, 'setup' | 'running'>, events: CombatEvent[]) => void;
  openSummonTray: () => void; closeSummonTray: () => void; closeSummonDetails: () => void; selectSummon: (id: string | null) => void; beginPlacement: (id: string) => void; beginSummonDrag: (id: string) => void; setHoveredBattleCell: (cell: BattleCell | null) => void; requestPlacement: (cell: BattleCell) => void; recallSummon: (id: string) => void; cancelPlacement: () => void;
  initializeBaseCamp: () => boolean; selectCampSummon: (id: string | null) => void; beginCampDrag: (id: string) => void; setHoveredCampCell: (cell: CampCell | null) => void; requestCampMove: (cell: CampCell) => boolean; cancelCampInteraction: () => void; replaceCampPlacements: (placements: CampPlacement[]) => void;
  reportPerformance: (performance: PerformanceSnapshot) => void; setTutorial: (stepId: string | null, completedStepIds: string[], context: TutorialContext) => void; restoreSetup: (inventory: SummonInstance[], placements: BattlefieldPlacement[], campPlacements?: CampPlacement[]) => void;
};

export function tutorialAllows(action: TutorialAction): boolean {
  const state = useGameStore.getState();
  return isTutorialActionAllowed({ currentStepId: state.tutorialStepId, completedStepIds: state.tutorialCompletedStepIds, context: state.tutorialContext }, action, tutorialDefinitions);
}
export function createInitialCampPlacements(inventory: readonly SummonInstance[], campaignPlacements: readonly BattlefieldPlacement[]): CampPlacement[] {
  const campaignIds = campaignPlacements.map((placement) => placement.summonInstanceId);
  const starterIds = inventory.filter((instance) => instance.id.startsWith('starter:')).map((instance) => instance.id);
  const ids = [...campaignIds, ...starterIds].filter((id, index, values) => values.indexOf(id) === index && inventory.some((instance) => instance.id === id)).slice(0, 6);
  return ids.map((summonInstanceId, x) => ({ summonInstanceId, cell: { x, y: 3 } }));
}

export const useGameStore = create<GameState>((set, get) => ({
  scene: 'campaign', debugOpen: false, autoCast: false, battlePhase: 'setup', battleSnapshot: null, battleEvents: [], battleTick: 0, readySkillActorIds: [], deadUnitIds: [], battleUnits: {}, inventory: createStarterSummonInstances(), placements: [], campPlacements: [], selectedSummonInstanceId: null, selectedCampSummonInstanceId: null, summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', campInteractionMode: 'idle', hoveredBattleCell: null, hoveredCampCell: null, tutorialStepId: 'campaign_open_inventory', tutorialCompletedStepIds: [], tutorialContext: {}, boardOccupancy: 0, boardCapacity: 64, balls: 100, ballCapacity: 100, simulationSeed: 'tutorial-001', performance: { fps: 0, frameTimeMs: 0 }, cameraPresetId: 'campaign_overview', cameraTransitioning: false,
  setScene: (scene) => { if (scene === 'campaign' || get().tutorialStepId === null) set({ scene }); }, setSceneInternal: (scene) => set({ scene }), setCameraPreset: (cameraPresetId, cameraTransitioning = true) => set({ cameraPresetId, cameraTransitioning }), setCameraTransitioning: (cameraTransitioning) => set({ cameraTransitioning }), toggleDebug: () => set((state) => ({ debugOpen: !state.debugOpen })), setAutoCast: (autoCast) => set({ autoCast }),
  beginBattle: (battleSnapshot, battleEvents, battleUnits) => set({ battlePhase: 'running', battleSnapshot, battleEvents, battleUnits, battleTick: 0, readySkillActorIds: [], deadUnitIds: [], autoCast: false, summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null, selectedSummonInstanceId: null }),
  updateBattle: (battleTick, events, battleUnits, readySkillActorIds, deadUnitIds) => set((state) => ({ battleTick, battleEvents: [...state.battleEvents, ...events], battleUnits, readySkillActorIds, deadUnitIds })), finishBattle: (battlePhase, events) => set((state) => ({ battlePhase, battleEvents: [...state.battleEvents, ...events], readySkillActorIds: [] })),
  openSummonTray: () => { if (get().battlePhase !== 'setup' || !tutorialAllows('OPEN_INVENTORY')) return; set({ summonTrayOpen: true }); emitGameInteraction({ type: 'INVENTORY_OPENED' }); }, closeSummonTray: () => set({ summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null }), closeSummonDetails: () => set({ summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null }),
  selectSummon: (selectedSummonInstanceId) => { if (get().battlePhase !== 'setup' || !tutorialAllows('SELECT_SUMMON')) return; set({ selectedSummonInstanceId, summonDetailsOpen: selectedSummonInstanceId !== null, placementMode: selectedSummonInstanceId === null ? 'idle' : 'selected', hoveredBattleCell: null }); if (selectedSummonInstanceId) emitGameInteraction({ type: 'SUMMON_SELECTED', summonInstanceId: selectedSummonInstanceId }); },
  beginPlacement: (selectedSummonInstanceId) => { if (get().battlePhase !== 'setup' || !(tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON'))) return; set({ selectedSummonInstanceId, summonDetailsOpen: true, placementMode: 'selected', hoveredBattleCell: null }); }, beginSummonDrag: (selectedSummonInstanceId) => { if (get().battlePhase !== 'setup' || !tutorialAllows('PLACE_SUMMON')) return; set({ selectedSummonInstanceId, summonTrayOpen: true, summonDetailsOpen: true, placementMode: 'dragging', hoveredBattleCell: null }); emitGameInteraction({ type: 'SUMMON_DRAG_STARTED', summonInstanceId: selectedSummonInstanceId }); },
  setHoveredBattleCell: (hoveredBattleCell) => set((state) => state.battlePhase !== 'setup' || sameBattleCell(state.hoveredBattleCell, hoveredBattleCell) ? state : { hoveredBattleCell }),
  requestPlacement: (cell) => { const state = get(); if (state.battlePhase !== 'setup' || !(tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON'))) return; const instanceId = state.selectedSummonInstanceId; if (!instanceId || !canDeploySummon(instanceId, cell, state.placements)) return; const placements = [...state.placements.filter((placement) => placement.summonInstanceId !== instanceId), { summonInstanceId: instanceId, cell }]; set({ placements, boardOccupancy: placements.length, placementMode: 'idle', summonDetailsOpen: false, summonTrayOpen: placements.length === 6 ? false : state.summonTrayOpen, hoveredBattleCell: null }); emitGameInteraction({ type: 'SUMMON_PLACED', summonInstanceId: instanceId }); if (placements.length === 6) emitGameInteraction({ type: 'TEAM_SIZE_6' }); },
  recallSummon: (id) => set((state) => { if (state.battlePhase !== 'setup' || !tutorialAllows('RECALL_SUMMON')) return state; const placements = recallBattlefieldPlacement(id, state.placements); return { placements, boardOccupancy: placements.length, placementMode: 'idle', hoveredBattleCell: null }; }), cancelPlacement: () => { if (get().battlePhase === 'setup') set({ placementMode: 'idle', hoveredBattleCell: null }); },
  initializeBaseCamp: () => { const state = get(); if (state.campPlacements.length > 0) return false; const campPlacements = createInitialCampPlacements(state.inventory, state.placements); if (campPlacements.length !== 6) return false; set({ campPlacements }); return true; },
  selectCampSummon: (selectedCampSummonInstanceId) => { const state = get(); if (selectedCampSummonInstanceId === null) { set({ selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }); return; } if (!tutorialAllows('SELECT_CAMP_SUMMON') || !getCampPlacementForSummon(selectedCampSummonInstanceId, state.campPlacements)) return; set({ selectedCampSummonInstanceId, campInteractionMode: 'selected', hoveredCampCell: null }); emitGameInteraction({ type: 'CAMP_SUMMON_SELECTED', summonInstanceId: selectedCampSummonInstanceId }); },
  beginCampDrag: (id) => { if (!tutorialAllows('SELECT_CAMP_SUMMON') || !getCampPlacementForSummon(id, get().campPlacements)) return; set({ selectedCampSummonInstanceId: id, campInteractionMode: 'dragging', hoveredCampCell: null }); emitGameInteraction({ type: 'CAMP_SUMMON_SELECTED', summonInstanceId: id }); }, setHoveredCampCell: (hoveredCampCell) => set((state) => state.hoveredCampCell?.x === hoveredCampCell?.x && state.hoveredCampCell?.y === hoveredCampCell?.y ? state : { hoveredCampCell }),
  requestCampMove: (cell) => { const state = get(); const id = state.selectedCampSummonInstanceId; const from = id ? getCampPlacementForSummon(id, state.campPlacements) : undefined; if (!id || !from || !tutorialAllows('MOVE_CAMP_SUMMON')) return false; if (state.tutorialStepId !== null && (!isIlluminatiCell(cell) || isIlluminatiCell(from.cell)) || !canPlaceCampSummon(id, cell, state.campPlacements)) return false; const campPlacements = moveCampSummon(id, cell, state.campPlacements); const becameFull = !isIlluminatiFull(state.campPlacements) && isIlluminatiFull(campPlacements); set({ campPlacements, selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }); emitGameInteraction({ type: 'CAMP_SUMMON_MOVED', summonInstanceId: id, from: from.cell, to: cell }); if (becameFull) emitGameInteraction({ type: 'ILLUMINATI_FULL' }); return true; },
  cancelCampInteraction: () => set({ selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }), replaceCampPlacements: (campPlacements) => set({ campPlacements, selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }), reportPerformance: (performance) => set({ performance }), setTutorial: (tutorialStepId, tutorialCompletedStepIds, tutorialContext) => set({ tutorialStepId, tutorialCompletedStepIds, tutorialContext }), restoreSetup: (inventory, placements, campPlacements = []) => set({ inventory, placements, campPlacements, boardOccupancy: placements.length }),
}));

export function getCampCounters(placements: readonly CampPlacement[]) { return { campOccupancy: countCampOccupancy(placements), campCapacity: 36, illuminatiOccupancy: countIlluminatiOccupancy(placements), illuminatiCapacity: 6 }; }
