import { create } from 'zustand';
import { createStarterSummonInstances, GAME_CONTENT_VERSION, tutorialDefinitions } from '@psyblr/game-content';
import { canDeploySummon, canMerge, canPlaceCampSummon, countCampOccupancy, countIlluminatiOccupancy, createEmptyRaidSquadDraft, finalizeRaidSquadDraft, getCampPlacementForSummon, isIlluminatiCell, isIlluminatiFull, moveCampSummon, recallBattlefieldPlacement, removeRaidSummon, sanitizeRaidDraft, selectRaidSummon as selectRaidSummonForRound } from '@psyblr/game-rules';
import { RaidSquadSnapshotSchema, type BattleCell, type BattlefieldPlacement, type CampCell, type CampPlacement, type CombatEvent, type CombatSnapshot, type MergeRuntimeSnapshot, type MergeSummonsResult, type RaidRoundId, type RaidSquadDraft, type RaidSquadSnapshot, type ReleaseBallResult, type SpawnRuntimeSnapshot, type SummonInstance, type TutorialAction } from '@psyblr/contracts';
import { isTutorialActionAllowed, type TutorialContext } from '@psyblr/tutorial-core';
import { sameBattleCell } from '../game/battlefield';
import type { CameraPresetId } from '../game/camera';
import { emitGameInteraction } from '../game/interactionEvents';
import { createTutorialSpawnRuntime } from '../spawn/gateway';
import { createTutorialMergeGateway } from '../merge/gateway';

export type SceneId = 'campaign' | 'base' | 'raid';
export type PerformanceSnapshot = { fps: number; frameTimeMs: number };
export type PlacementMode = 'idle' | 'selected' | 'dragging';
export type BattlePhase = 'setup' | 'running' | 'victory' | 'defeat' | 'draw';
export type BattleUnitView = { id: string; hp: number; maxHp: number; x: number; z: number; dead: boolean; shield: number };

type GameState = {
  scene: SceneId; debugOpen: boolean; autoCast: boolean; battlePhase: BattlePhase; battleSnapshot: CombatSnapshot | null; battleEvents: CombatEvent[]; battleTick: number; readySkillActorIds: string[]; deadUnitIds: string[]; battleUnits: Record<string, BattleUnitView>;
  inventory: SummonInstance[]; placements: BattlefieldPlacement[]; campPlacements: CampPlacement[];
  selectedSummonInstanceId: string | null; selectedCampSummonInstanceId: string | null; summonTrayOpen: boolean; summonDetailsOpen: boolean; placementMode: PlacementMode; campInteractionMode: PlacementMode; hoveredBattleCell: BattleCell | null; hoveredCampCell: CampCell | null;
  tutorialStepId: string | null; tutorialCompletedStepIds: string[]; tutorialContext: TutorialContext; boardOccupancy: number; boardCapacity: number; spawn: SpawnRuntimeSnapshot; spawnOpen: boolean; spawnError: string | null; merge: MergeRuntimeSnapshot; mergePendingIds: string[]; mergeError: string | null; mergePresentation: MergeSummonsResult | null; simulationSeed: string; performance: PerformanceSnapshot; cameraPresetId: CameraPresetId; cameraTransitioning: boolean;
  raidDraft: RaidSquadDraft; raidSnapshot: RaidSquadSnapshot | null; raidError: string | null;
  setScene: (scene: SceneId) => void; setSceneInternal: (scene: SceneId) => void; setCameraPreset: (preset: CameraPresetId, transitioning?: boolean) => void; setCameraTransitioning: (transitioning: boolean) => void; toggleDebug: () => void; setAutoCast: (autoCast: boolean) => void;
  beginBattle: (snapshot: CombatSnapshot, events: CombatEvent[], units: Record<string, BattleUnitView>) => void; updateBattle: (tick: number, events: CombatEvent[], units: Record<string, BattleUnitView>, readySkillActorIds: string[], deadUnitIds: string[]) => void; finishBattle: (phase: Exclude<BattlePhase, 'setup' | 'running'>, events: CombatEvent[]) => void;
  openSummonTray: () => void; closeSummonTray: () => void; closeSummonDetails: () => void; selectSummon: (id: string | null) => void; beginPlacement: (id: string) => void; beginSummonDrag: (id: string) => void; setHoveredBattleCell: (cell: BattleCell | null) => void; requestPlacement: (cell: BattleCell) => void; recallSummon: (id: string) => void; cancelPlacement: () => void;
  initializeBaseCamp: () => boolean; selectCampSummon: (id: string | null) => void; beginCampDrag: (id: string) => void; setHoveredCampCell: (cell: CampCell | null) => void; requestCampMove: (cell: CampCell) => boolean; requestMerge: (sourceId: string, targetId: string) => Promise<boolean>; applyMergeResult: (result: MergeSummonsResult) => boolean; cancelCampInteraction: () => void; replaceCampPlacements: (placements: CampPlacement[]) => void;
  reportPerformance: (performance: PerformanceSnapshot) => void; setTutorial: (stepId: string | null, completedStepIds: string[], context: TutorialContext) => void; restoreSetup: (inventory: SummonInstance[], placements: BattlefieldPlacement[], campPlacements?: CampPlacement[], spawn?: SpawnRuntimeSnapshot, merge?: MergeRuntimeSnapshot, raidDraft?: RaidSquadDraft, raidSnapshot?: RaidSquadSnapshot | null) => void;
  openSpawnMachine: () => void; closeSpawnMachine: () => void; setSpawnError: (error: string | null) => void; applySpawnRelease: (result: ReleaseBallResult) => boolean;
  openRaidGate: () => void; selectRaidSummon: (roundId: RaidRoundId, instanceId: string) => boolean; removeRaidSummon: (roundId: RaidRoundId, slotIndex: number) => void; startRaid: () => boolean;
};

export function tutorialAllows(action: TutorialAction): boolean {
  const state = useGameStore.getState();
  return isTutorialActionAllowed({ currentStepId: state.tutorialStepId, completedStepIds: state.tutorialCompletedStepIds, context: state.tutorialContext }, action, tutorialDefinitions);
}
export function createInitialCampPlacements(inventory: readonly SummonInstance[], campaignPlacements: readonly BattlefieldPlacement[]): CampPlacement[] {
  const campaignIds = campaignPlacements.map((placement) => placement.summonInstanceId);
  const starterIds = inventory.filter((instance) => instance.id.startsWith('starter:')).map((instance) => instance.id);
  const ids = [...campaignIds, ...starterIds].filter((id, index, values) => values.indexOf(id) === index && inventory.some((instance) => instance.id === id)).slice(0, 6);
  return ids.map((summonInstanceId, x) => ({ summonInstanceId, cell: { x, y: 3 } }));
}

export const useGameStore = create<GameState>((set, get) => ({
  scene: 'campaign', debugOpen: false, autoCast: false, battlePhase: 'setup', battleSnapshot: null, battleEvents: [], battleTick: 0, readySkillActorIds: [], deadUnitIds: [], battleUnits: {}, inventory: createStarterSummonInstances(), placements: [], campPlacements: [], selectedSummonInstanceId: null, selectedCampSummonInstanceId: null, summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', campInteractionMode: 'idle', hoveredBattleCell: null, hoveredCampCell: null, tutorialStepId: 'campaign_open_inventory', tutorialCompletedStepIds: [], tutorialContext: {}, boardOccupancy: 0, boardCapacity: 64, spawn: createTutorialSpawnRuntime(), spawnOpen: false, spawnError: null, merge: { appliedActionIds: [] }, mergePendingIds: [], mergeError: null, mergePresentation: null, raidDraft: createEmptyRaidSquadDraft(), raidSnapshot: null, raidError: null, simulationSeed: 'tutorial-001', performance: { fps: 0, frameTimeMs: 0 }, cameraPresetId: 'campaign_overview', cameraTransitioning: false,
  setScene: (scene) => { if (scene === 'campaign' || get().tutorialStepId === null) set({ scene, ...(scene === 'raid' ? { cameraPresetId: 'raid_overview' as const, cameraTransitioning: true } : {}) }); }, setSceneInternal: (scene) => set({ scene }), setCameraPreset: (cameraPresetId, cameraTransitioning = true) => set({ cameraPresetId, cameraTransitioning }), setCameraTransitioning: (cameraTransitioning) => set({ cameraTransitioning }), toggleDebug: () => set((state) => ({ debugOpen: !state.debugOpen })), setAutoCast: (autoCast) => set({ autoCast }),
  beginBattle: (battleSnapshot, battleEvents, battleUnits) => set({ battlePhase: 'running', battleSnapshot, battleEvents, battleUnits, battleTick: 0, readySkillActorIds: [], deadUnitIds: [], autoCast: false, summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null, selectedSummonInstanceId: null }),
  updateBattle: (battleTick, events, battleUnits, readySkillActorIds, deadUnitIds) => set((state) => ({ battleTick, battleEvents: [...state.battleEvents, ...events], battleUnits, readySkillActorIds, deadUnitIds })), finishBattle: (battlePhase, events) => set((state) => ({ battlePhase, battleEvents: [...state.battleEvents, ...events], readySkillActorIds: [] })),
  openSummonTray: () => { if (get().battlePhase !== 'setup' || !tutorialAllows('OPEN_INVENTORY')) return; set({ summonTrayOpen: true }); emitGameInteraction({ type: 'INVENTORY_OPENED' }); }, closeSummonTray: () => set({ summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null }), closeSummonDetails: () => set({ summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null }),
  selectSummon: (selectedSummonInstanceId) => { if (get().battlePhase !== 'setup' || !tutorialAllows('SELECT_SUMMON')) return; set({ selectedSummonInstanceId, summonDetailsOpen: selectedSummonInstanceId !== null, placementMode: selectedSummonInstanceId === null ? 'idle' : 'selected', hoveredBattleCell: null }); if (selectedSummonInstanceId) emitGameInteraction({ type: 'SUMMON_SELECTED', summonInstanceId: selectedSummonInstanceId }); },
  beginPlacement: (selectedSummonInstanceId) => { if (get().battlePhase !== 'setup' || !(tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON'))) return; set({ selectedSummonInstanceId, summonDetailsOpen: true, placementMode: 'selected', hoveredBattleCell: null }); }, beginSummonDrag: (selectedSummonInstanceId) => { if (get().battlePhase !== 'setup' || !tutorialAllows('PLACE_SUMMON')) return; set({ selectedSummonInstanceId, summonTrayOpen: true, summonDetailsOpen: true, placementMode: 'dragging', hoveredBattleCell: null }); emitGameInteraction({ type: 'SUMMON_DRAG_STARTED', summonInstanceId: selectedSummonInstanceId }); },
  setHoveredBattleCell: (hoveredBattleCell) => set((state) => state.battlePhase !== 'setup' || sameBattleCell(state.hoveredBattleCell, hoveredBattleCell) ? state : { hoveredBattleCell }),
  requestPlacement: (cell) => { const state = get(); if (state.battlePhase !== 'setup' || !(tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON'))) return; const instanceId = state.selectedSummonInstanceId; if (!instanceId || !canDeploySummon(instanceId, cell, state.placements)) return; const placements = [...state.placements.filter((placement) => placement.summonInstanceId !== instanceId), { summonInstanceId: instanceId, cell }]; set({ placements, boardOccupancy: placements.length, placementMode: 'idle', summonDetailsOpen: false, summonTrayOpen: placements.length === 6 ? false : state.summonTrayOpen, hoveredBattleCell: null }); emitGameInteraction({ type: 'SUMMON_PLACED', summonInstanceId: instanceId }); if (placements.length === 6) emitGameInteraction({ type: 'TEAM_SIZE_6' }); },
  recallSummon: (id) => set((state) => { if (state.battlePhase !== 'setup' || !tutorialAllows('RECALL_SUMMON')) return state; const placements = recallBattlefieldPlacement(id, state.placements); return { placements, boardOccupancy: placements.length, placementMode: 'idle', hoveredBattleCell: null }; }), cancelPlacement: () => { if (get().battlePhase === 'setup') set({ placementMode: 'idle', hoveredBattleCell: null }); },
  initializeBaseCamp: () => { const state = get(); if (state.campPlacements.length > 0) return false; const campPlacements = createInitialCampPlacements(state.inventory, state.placements); if (campPlacements.length !== 6) return false; set({ campPlacements }); return true; },
  selectCampSummon: (selectedCampSummonInstanceId) => { const state = get(); if (selectedCampSummonInstanceId === null) { set({ selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }); return; } if (state.mergePendingIds.includes(selectedCampSummonInstanceId) || !tutorialAllows('SELECT_CAMP_SUMMON') || !getCampPlacementForSummon(selectedCampSummonInstanceId, state.campPlacements)) return; set({ selectedCampSummonInstanceId, campInteractionMode: 'selected', hoveredCampCell: null, mergeError: null }); emitGameInteraction({ type: 'CAMP_SUMMON_SELECTED', summonInstanceId: selectedCampSummonInstanceId }); },
  beginCampDrag: (id) => { const state = get(); if (state.mergePendingIds.includes(id) || !tutorialAllows('SELECT_CAMP_SUMMON') || !getCampPlacementForSummon(id, state.campPlacements)) return; set({ selectedCampSummonInstanceId: id, campInteractionMode: 'dragging', hoveredCampCell: null, mergeError: null }); emitGameInteraction({ type: 'CAMP_SUMMON_SELECTED', summonInstanceId: id }); }, setHoveredCampCell: (hoveredCampCell) => set((state) => state.hoveredCampCell?.x === hoveredCampCell?.x && state.hoveredCampCell?.y === hoveredCampCell?.y ? state : { hoveredCampCell }),
  requestCampMove: (cell) => { const state = get(); const id = state.selectedCampSummonInstanceId; const from = id ? getCampPlacementForSummon(id, state.campPlacements) : undefined; if (!id || !from) return false; const destination = state.campPlacements.find((entry) => entry.cell.x === cell.x && entry.cell.y === cell.y); const target = destination && state.inventory.find((entry) => entry.id === destination.summonInstanceId); const source = state.inventory.find((entry) => entry.id === id); if (target && source) { if (tutorialAllows('MERGE_SUMMONS') && canMerge(source, target)) { void get().requestMerge(id, target.id); return true; } if (tutorialAllows('MERGE_SUMMONS')) { const mergeError = source.definitionId !== target.definitionId || source.tier !== target.tier ? 'Needs same Summon and tier' : 'Max tier reached'; set({ mergeError, campInteractionMode: 'selected', hoveredCampCell: null }); clearMergeFeedback(get, set, mergeError); return false; } }
    if (!tutorialAllows('MOVE_CAMP_SUMMON')) return false; if (state.tutorialStepId !== null && (!isIlluminatiCell(cell) || isIlluminatiCell(from.cell)) || !canPlaceCampSummon(id, cell, state.campPlacements)) { const mergeError = 'That camp cell is unavailable'; set({ mergeError }); clearMergeFeedback(get, set, mergeError); return false; } const campPlacements = moveCampSummon(id, cell, state.campPlacements); const becameFull = !isIlluminatiFull(state.campPlacements) && isIlluminatiFull(campPlacements); set({ campPlacements, selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }); emitGameInteraction({ type: 'CAMP_SUMMON_MOVED', summonInstanceId: id, from: from.cell, to: cell }); if (becameFull) emitGameInteraction({ type: 'ILLUMINATI_FULL' }); return true; },
  requestMerge: async (sourceId, targetId) => { const state = get(); if (!tutorialAllows('MERGE_SUMMONS') || state.mergePendingIds.includes(sourceId) || state.mergePendingIds.includes(targetId)) return false; set({ mergePendingIds: [...state.mergePendingIds, sourceId, targetId], mergeError: null }); const actionId = `tutorial-merge-${state.merge.appliedActionIds.length + 1}-${++mergeActionSequence}`; try { return get().applyMergeResult(await tutorialMergeGateway.mergeSummons({ clientActionId: actionId, sourceSummonInstanceId: sourceId, targetSummonInstanceId: targetId })); } catch (cause) { const mergeError = cause instanceof Error ? cause.message : 'Merge failed. Retry.'; set((current) => ({ mergePendingIds: current.mergePendingIds.filter((id) => id !== sourceId && id !== targetId), mergeError })); clearMergeFeedback(get, set, mergeError); return false; } },
  applyMergeResult: (result) => { const state = get(); if (state.merge.appliedActionIds.includes(result.clientActionId)) return false; const source = state.inventory.find((entry) => entry.id === result.consumedSourceInstanceId); const target = state.inventory.find((entry) => entry.id === result.upgradedTarget.id); if (!source || !target || !getCampPlacementForSummon(source.id, state.campPlacements) || !getCampPlacementForSummon(target.id, state.campPlacements)) return false; const placements = state.placements.map((placement) => placement.summonInstanceId === source.id ? { ...placement, summonInstanceId: target.id } : placement).filter((placement, index, values) => values.findIndex((candidate) => candidate.summonInstanceId === placement.summonInstanceId) === index); const campPlacements = [...state.campPlacements.filter((placement) => placement.summonInstanceId !== source.id && placement.summonInstanceId !== target.id), result.targetPlacement]; const inventory = state.inventory.filter((entry) => entry.id !== source.id && entry.id !== target.id).concat(result.upgradedTarget); const merge = { appliedActionIds: [...state.merge.appliedActionIds, result.clientActionId] }; tutorialMergeGateway.acknowledge(result); set({ inventory, placements, campPlacements, boardOccupancy: placements.length, merge, mergePendingIds: state.mergePendingIds.filter((id) => id !== source.id && id !== target.id), mergeError: null, mergePresentation: result, selectedSummonInstanceId: state.selectedSummonInstanceId === source.id ? target.id : state.selectedSummonInstanceId, selectedCampSummonInstanceId: target.id, campInteractionMode: 'selected', hoveredCampCell: null }); globalThis.setTimeout(() => { if (get().mergePresentation?.clientActionId === result.clientActionId) set({ mergePresentation: null }); }, 850); emitGameInteraction({ type: 'MERGE_COMPLETED', definitionId: target.definitionId, sourceId: source.id, targetId: target.id, fromTier: result.previousTier, toTier: result.nextTier }); return true; },
  cancelCampInteraction: () => set({ selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }), replaceCampPlacements: (campPlacements) => set({ campPlacements, selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }), reportPerformance: (performance) => set({ performance }), setTutorial: (tutorialStepId, tutorialCompletedStepIds, tutorialContext) => set({ tutorialStepId, tutorialCompletedStepIds, tutorialContext }), restoreSetup: (inventory, placements, campPlacements = [], spawn = createTutorialSpawnRuntime(), merge = { appliedActionIds: [] }, raidDraft = createEmptyRaidSquadDraft(), raidSnapshot: RaidSquadSnapshot | null = null) => { const restoredRaid = sanitizeRaidDraft(raidDraft, inventory); const parsedSnapshot = raidSnapshot ? RaidSquadSnapshotSchema.safeParse(raidSnapshot) : null; const raidError = restoredRaid.error ?? (raidSnapshot && !parsedSnapshot?.success ? 'Locked raid squad was invalid and was cleared.' : null); set({ inventory, placements, campPlacements, spawn, merge, raidDraft: restoredRaid.draft, raidSnapshot: parsedSnapshot?.success ? parsedSnapshot.data : null, raidError, mergePendingIds: [], mergeError: null, mergePresentation: null, boardOccupancy: placements.length }); },
  openSpawnMachine: () => { const state = get(); if (state.cameraTransitioning || !tutorialAllows('OPEN_SPAWN_MACHINE')) return; set({ spawnOpen: true, spawnError: null }); emitGameInteraction({ type: 'SPAWN_UI_OPENED' }); }, closeSpawnMachine: () => set({ spawnOpen: false, spawnError: null }), setSpawnError: (spawnError) => set({ spawnError }),
  applySpawnRelease: (result) => { const state = get(); if (state.spawn.appliedActionIds.includes(result.clientActionId) || state.inventory.some((entry) => entry.id === result.createdSummon.id)) return false; const campPlacements = [...state.campPlacements, result.destination]; const spawn = { ...state.spawn, balls: result.ballsRemaining, blobProgress: result.blobProgress, tutorialDropIndex: state.spawn.tutorialDropIndex + 1, appliedActionIds: [...state.spawn.appliedActionIds, result.clientActionId] }; set({ inventory: [...state.inventory, result.createdSummon], campPlacements, spawn, spawnError: null }); emitGameInteraction({ type: 'BALL_DROPPED' }); if (campPlacements.length === 36) emitGameInteraction({ type: 'CAMP_FULL' }); return true; },
  openRaidGate: () => { const state = get(); if (state.cameraTransitioning || !tutorialAllows('OPEN_RAID_GATE')) return; set({ scene: 'raid', cameraPresetId: 'raid_overview', cameraTransitioning: true, spawnOpen: false, raidError: null }); emitGameInteraction({ type: 'RAID_GATE_OPENED' }); },
  selectRaidSummon: (roundId, instanceId) => { const state = get(); if (state.raidSnapshot || !tutorialAllows('SELECT_RAID_SUMMON')) return false; const result = selectRaidSummonForRound(state.raidDraft, roundId, instanceId, state.inventory); set({ raidDraft: result.draft, raidError: result.error }); if (!result.error) emitGameInteraction({ type: 'RAID_SUMMON_SELECTED', roundId, summonInstanceId: instanceId }); return !result.error; },
  removeRaidSummon: (roundId, slotIndex) => { const state = get(); if (state.raidSnapshot || !tutorialAllows('SELECT_RAID_SUMMON')) return; const result = removeRaidSummon(state.raidDraft, roundId, slotIndex); set({ raidDraft: result.draft, raidError: result.error }); },
  startRaid: () => { const state = get(); if (state.raidSnapshot) return true; if (!tutorialAllows('START_RAID')) return false; const clientActionId = `tutorial-raid-${++raidActionSequence}`; const result = finalizeRaidSquadDraft(state.raidDraft, state.inventory, clientActionId, GAME_CONTENT_VERSION); if (!result.ok) { set({ raidError: result.error }); return false; } set({ raidSnapshot: result.snapshot, raidError: null }); emitGameInteraction({ type: 'RAID_STARTED', clientActionId }); return true; },
}));

let mergeActionSequence = 0;
let raidActionSequence = 0;
const tutorialMergeGateway = createTutorialMergeGateway(() => { const state = useGameStore.getState(); return { merge: state.merge, inventory: state.inventory, campPlacements: state.campPlacements }; });
function clearMergeFeedback(get: () => GameState, set: (partial: Partial<GameState>) => void, message: string) { globalThis.setTimeout(() => { if (get().mergeError === message) set({ mergeError: null }); }, 1800); }

export function getCampCounters(placements: readonly CampPlacement[]) { return { campOccupancy: countCampOccupancy(placements), campCapacity: 36, illuminatiOccupancy: countIlluminatiOccupancy(placements), illuminatiCapacity: 6 }; }
