import { useEffect, useRef, useState } from 'react';
import { getSummonDefinition } from '@psyblr/game-content';
import { tutorialAllows, useGameStore } from '../stores/gameStore';
import { createTutorialSpawnGateway } from '../spawn/gateway';
import { dispatchTutorialEvent } from '../tutorial/controller';
import './spawn.css';

const HOLD_MS = 260;
export function SpawnMachineOverlay() {
  const open = useGameStore((state) => state.spawnOpen); const spawn = useGameStore((state) => state.spawn); const camp = useGameStore((state) => state.campPlacements); const inventory = useGameStore((state) => state.inventory); const context = useGameStore((state) => state.tutorialContext); const step = useGameStore((state) => state.tutorialStepId); const apply = useGameStore((state) => state.applySpawnRelease); const setError = useGameStore((state) => state.setSpawnError); const error = useGameStore((state) => state.spawnError);
  const [releasing, setReleasing] = useState(false); const held = useRef(false); const holdTimer = useRef<number | null>(null); const sequence = useRef(0);
  const announcedOpen = useRef(false);
  useEffect(() => { if (open && step === 'spawn_open' && !announcedOpen.current) { announcedOpen.current = true; dispatchTutorialEvent({ type: 'SPAWN_UI_OPENED' }); } if (!open) announcedOpen.current = false; }, [open, step]);
  const release = async () => { if (releasing || !tutorialAllows('DROP_BALL') || spawn.balls <= 0 || camp.length >= 36) return; setReleasing(true); const first = inventory.find((item) => item.id === context.firstSummonInstanceId); const primaryDefinitionId = first?.definitionId ?? spawn.dailyPool[0]!.summonDefinitionId; const gateway = createTutorialSpawnGateway(() => ({ runtime: useGameStore.getState().spawn, inventory: useGameStore.getState().inventory, campPlacements: useGameStore.getState().campPlacements, primaryDefinitionId })); const clientActionId = `tutorial-release-${spawn.tutorialDropIndex + 1}-${++sequence.current}`; try { apply(await gateway.releaseBall({ clientActionId })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Release failed. Retry.'); held.current = false; } finally { setReleasing(false); } };
  useEffect(() => { const loop = () => { if (!held.current || useGameStore.getState().tutorialStepId !== 'spawn_long_press') return; void release().finally(() => { if (held.current) window.setTimeout(loop, 55); }); }; const down = (event: KeyboardEvent) => { if ((event.key === ' ' || event.key === 'Enter') && open) { event.preventDefault(); held.current = true; void release(); holdTimer.current = window.setTimeout(loop, HOLD_MS); } }; const up = () => { held.current = false; if (holdTimer.current) window.clearTimeout(holdTimer.current); }; window.addEventListener('keydown', down); window.addEventListener('keyup', up); window.addEventListener('blur', up); return () => { window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); window.removeEventListener('blur', up); up(); }; });
  if (!open) return null;
  const onDown = () => { if (releasing) return; held.current = true; void release(); holdTimer.current = window.setTimeout(() => { const loop = () => { if (!held.current || useGameStore.getState().tutorialStepId !== 'spawn_long_press') return; void release().finally(() => { if (held.current) window.setTimeout(loop, 55); }); }; loop(); }, HOLD_MS); };
  const stop = () => { held.current = false; if (holdTimer.current) window.clearTimeout(holdTimer.current); };
  return <aside className="spawn-overlay" aria-label="Spawn Machine" data-testid="spawn-overlay"><header><span>SPAWN MACHINE</span><strong>{spawn.balls} / {spawn.ballCapacity}</strong><small>BATTLE CAMP {camp.length} / 36</small></header><div className="spawn-meter"><i style={{ width: `${spawn.balls / spawn.ballCapacity * 100}%` }} /></div><div className="spawn-slots">{spawn.dailyPool.map((slot) => { const definition = getSummonDefinition(slot.summonDefinitionId); return <article key={slot.slotIndex} data-testid={`spawn-slot-${slot.slotIndex}`}><b>{definition.displayName.slice(0, 1)}</b><span>{definition.displayName}</span><em>{slot.probability}%</em></article>; })}</div>{step === 'spawn_long_press' && <p>HOLD TO AUTO-DROP</p>}{error && <div className="spawn-error">{error} <button onClick={() => { setError(null); void release(); }}>RETRY</button></div>}<button className="spawn-drop" type="button" data-tutorial-target="drop-button" data-testid="drop-ball" disabled={releasing || spawn.balls <= 0 || camp.length >= 36 || !tutorialAllows('DROP_BALL')} onPointerDown={onDown} onPointerUp={stop} onPointerCancel={stop} onPointerLeave={stop}>DROP BALL</button></aside>;
}
