import { create } from 'zustand';
import { createStarterSummonInstances, GAME_CONTENT_VERSION, tutorialDefinitions } from '@psyblr/game-content';
import { canDeploySummon, canMerge, canPlaceCampSummon, countCampOccupancy, countIlluminatiOccupancy, createEmptyRaidSquadDraft, finalizeRaidRoundDraft, finalizeRaidSquadDraft, getCampPlacementForSummon, isBattleCellOccupied, isIlluminatiCell, isIlluminatiFull, isPlayerDeploymentCell, moveCampSummon, RAID_ROUND_DEFINITIONS, recallBattlefieldPlacement, removeRaidSummon, sanitizeRaidDraft } from '@psyblr/game-rules';
import { RaidResultSchema, RaidSquadSnapshotSchema, type BattleCell, type BattlefieldPlacement, type CampCell, type CampPlacement, type ClaimRaidStealResult, type CombatEvent, type CombatSnapshot, type MergeRuntimeSnapshot, type MergeSummonsResult, type OpponentCampHandoff, type RaidOpponent, type RaidResult, type RaidRoundId, type RaidRoundResolution, type RaidRoundResult, type RaidSquadDraft, type RaidSquadSnapshot, type ReleaseBallResult, type SpawnRuntimeSnapshot, type SummonInstance, type TutorialAction } from '@psyblr/contracts';
import { isTutorialActionAllowed, type TutorialContext } from '@psyblr/tutorial-core';
import { sameBattleCell } from '../game/battlefield';
import type { CameraPresetId } from '../game/camera';
import { emitGameInteraction } from '../game/interactionEvents';
import { createTutorialSpawnRuntime } from '../spawn/gateway';
import { createTutorialMergeGateway } from '../merge/gateway';
import { tutorialRaidGateway } from '../raid/gateway';
import { startRaidRoundReplay } from '../raid/replay';
import { resolveRaidOutcome } from '@psyblr/raid-core';

export type SceneId = 'campaign' | 'base' | 'raid' | 'opponentCamp';
export type PerformanceSnapshot = { fps: number; frameTimeMs: number };
export type PlacementMode = 'idle' | 'selected' | 'dragging';
export type BattlePhase = 'setup' | 'running' | 'victory' | 'defeat' | 'draw';
export type BattleUnitView = { id: string; hp: number; maxHp: number; x: number; z: number; dead: boolean; shield: number };
export type RaidStatus = 'setup' | 'resolving' | 'replaying' | 'complete' | 'error';

type GameState = {
  scene: SceneId; debugOpen: boolean; autoCast: boolean; battlePhase: BattlePhase; battleSnapshot: CombatSnapshot | null; battleEvents: CombatEvent[]; battleTick: number; readySkillActorIds: string[]; deadUnitIds: string[]; battleUnits: Record<string, BattleUnitView>;
  inventory: SummonInstance[]; placements: BattlefieldPlacement[]; campPlacements: CampPlacement[];
  selectedSummonInstanceId: string | null; selectedCampSummonInstanceId: string | null; summonTrayOpen: boolean; summonDetailsOpen: boolean; placementMode: PlacementMode; campInteractionMode: PlacementMode; hoveredBattleCell: BattleCell | null; hoveredCampCell: CampCell | null;
  tutorialStepId: string | null; tutorialCompletedStepIds: string[]; tutorialContext: TutorialContext; boardOccupancy: number; boardCapacity: number; spawn: SpawnRuntimeSnapshot; spawnOpen: boolean; spawnError: string | null; merge: MergeRuntimeSnapshot; mergePendingIds: string[]; mergeError: string | null; mergePresentation: MergeSummonsResult | null; simulationSeed: string; performance: PerformanceSnapshot; cameraPresetId: CameraPresetId; cameraTransitioning: boolean;
  raidDraft: RaidSquadDraft; raidFieldPlacements: Record<RaidRoundId, BattlefieldPlacement[]>; selectedRaidSummonInstanceId: string | null; hoveredRaidCell: BattleCell | null; raidSnapshot: RaidSquadSnapshot | null; raidResult: RaidResult | null; raidRoundResults: RaidRoundResult[]; raidRoundResolutions: RaidRoundResolution[]; raidSessionId: string | null; raidRootSeed: string | null; raidOpponent: RaidOpponent | null; raidStatus: RaidStatus; raidReplayRoundIndex: number; raidReplayUnits: Record<string, BattleUnitView>; raidError: string | null; raidWinEmitted: boolean;
  opponentCamp: OpponentCampHandoff | null; selectedStealTargetId: string | null; stealResult: ClaimRaidStealResult | null;
  setScene: (scene: SceneId) => void; setSceneInternal: (scene: SceneId) => void; setCameraPreset: (preset: CameraPresetId, transitioning?: boolean) => void; setCameraTransitioning: (transitioning: boolean) => void; toggleDebug: () => void; setAutoCast: (autoCast: boolean) => void;
  beginBattle: (snapshot: CombatSnapshot, events: CombatEvent[], units: Record<string, BattleUnitView>) => void; updateBattle: (tick: number, events: CombatEvent[], units: Record<string, BattleUnitView>, readySkillActorIds: string[], deadUnitIds: string[]) => void; finishBattle: (phase: Exclude<BattlePhase, 'setup' | 'running'>, events: CombatEvent[]) => void;
  openSummonTray: () => void; closeSummonTray: () => void; closeSummonDetails: () => void; selectSummon: (id: string | null) => void; beginPlacement: (id: string) => void; beginSummonDrag: (id: string) => void; setHoveredBattleCell: (cell: BattleCell | null) => void; requestPlacement: (cell: BattleCell) => void; recallSummon: (id: string) => void; cancelPlacement: () => void;
  initializeBaseCamp: () => boolean; selectCampSummon: (id: string | null) => void; beginCampDrag: (id: string) => void; setHoveredCampCell: (cell: CampCell | null) => void; requestCampMove: (cell: CampCell) => boolean; requestMerge: (sourceId: string, targetId: string) => Promise<boolean>; applyMergeResult: (result: MergeSummonsResult) => boolean; cancelCampInteraction: () => void; replaceCampPlacements: (placements: CampPlacement[]) => void;
  reportPerformance: (performance: PerformanceSnapshot) => void; setTutorial: (stepId: string | null, completedStepIds: string[], context: TutorialContext) => void; restoreSetup: (inventory: SummonInstance[], placements: BattlefieldPlacement[], campPlacements?: CampPlacement[], spawn?: SpawnRuntimeSnapshot, merge?: MergeRuntimeSnapshot, raidDraft?: RaidSquadDraft, raidSnapshot?: RaidSquadSnapshot | null, raidResult?: RaidResult | null) => void;
  openSpawnMachine: () => void; closeSpawnMachine: () => void; setSpawnError: (error: string | null) => void; applySpawnRelease: (result: ReleaseBallResult) => boolean;
  openRaidGate: () => void; selectRaidSummon: (roundId: RaidRoundId, instanceId: string) => boolean; requestRaidPlacement: (cell: BattleCell) => boolean; setHoveredRaidCell: (cell: BattleCell | null) => void; removeRaidSummon: (roundId: RaidRoundId, slotIndex: number) => void; startRaid: () => boolean; retryRaid: () => void; finishRaidRoundReplay: () => void;
  openOpponentCamp: () => void; selectStealTarget: (id: string) => void; claimSteal: () => boolean; cancelSteal: () => void;
};

export function tutorialAllows(action: TutorialAction): boolean {
  const state = useGameStore.getState();
  return isTutorialActionAllowed({ currentStepId: state.tutorialStepId, completedStepIds: state.tutorialCompletedStepIds, context: state.tutorialContext }, action, tutorialDefinitions);
}
export function createInitialCampPlacements(inventory: readonly SummonInstance[], campaignPlacements: readonly BattlefieldPlacement[]): CampPlacement[] {
  const campaignIds = campaignPlacements.map((placement) => placement.summonInstanceId);
  const starterIds = inventory.filter((instance) => instance.id.startsWith('starter:')).map((instance) => instance.id);
  const ids = [...campaignIds, ...starterIds].filter((id, index, values) => values.indexOf(id) === index && inventory.some((instance) => instance.id === id)).slice(0, 6);
  return ids.map((summonInstanceId, x) => ({ summonInstanceId, cell: { x, y: 3 } }));
}

export const useGameStore = create<GameState>((set, get) => ({
  scene: 'campaign', debugOpen: false, autoCast: false, battlePhase: 'setup', battleSnapshot: null, battleEvents: [], battleTick: 0, readySkillActorIds: [], deadUnitIds: [], battleUnits: {}, inventory: createStarterSummonInstances(), placements: [], campPlacements: [], selectedSummonInstanceId: null, selectedCampSummonInstanceId: null, summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', campInteractionMode: 'idle', hoveredBattleCell: null, hoveredCampCell: null, tutorialStepId: 'campaign_open_inventory', tutorialCompletedStepIds: [], tutorialContext: {}, boardOccupancy: 0, boardCapacity: 64, spawn: createTutorialSpawnRuntime(), spawnOpen: false, spawnError: null, merge: { appliedActionIds: [] }, mergePendingIds: [], mergeError: null, mergePresentation: null, raidDraft: createEmptyRaidSquadDraft(), raidFieldPlacements: createEmptyRaidFieldPlacements(), selectedRaidSummonInstanceId: null, hoveredRaidCell: null, raidSnapshot: null, raidResult: null, raidRoundResults: [], raidRoundResolutions: [], raidSessionId: null, raidRootSeed: null, raidOpponent: null, raidStatus: 'setup', raidReplayRoundIndex: 0, raidReplayUnits: {}, raidError: null, raidWinEmitted: false, simulationSeed: 'tutorial-001', performance: { fps: 0, frameTimeMs: 0 }, cameraPresetId: 'campaign_deployment', cameraTransitioning: false,
  opponentCamp: null, selectedStealTargetId: null, stealResult: null,
  setScene: (scene) => { if (scene === 'campaign' || get().tutorialStepId === null) set({ scene, ...((scene === 'raid' || scene === 'opponentCamp') ? { cameraPresetId: 'raid_overview' as const, cameraTransitioning: true } : {}) }); }, setSceneInternal: (scene) => set({ scene }), setCameraPreset: (cameraPresetId, cameraTransitioning = true) => set({ cameraPresetId, cameraTransitioning }), setCameraTransitioning: (cameraTransitioning) => set({ cameraTransitioning }), toggleDebug: () => set((state) => ({ debugOpen: !state.debugOpen })), setAutoCast: (autoCast) => set({ autoCast }),
  beginBattle: (battleSnapshot, battleEvents, battleUnits) => set({ battlePhase: 'running', battleSnapshot, battleEvents, battleUnits, battleTick: 0, readySkillActorIds: [], deadUnitIds: [], autoCast: false, summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null, selectedSummonInstanceId: null, cameraPresetId: 'campaign_overview', cameraTransitioning: true }),
  updateBattle: (battleTick, events, battleUnits, readySkillActorIds, deadUnitIds) => set((state) => ({ battleTick, battleEvents: [...state.battleEvents, ...events], battleUnits, readySkillActorIds, deadUnitIds })), finishBattle: (battlePhase, events) => set((state) => ({ battlePhase, battleEvents: [...state.battleEvents, ...events], readySkillActorIds: [] })),
  openSummonTray: () => { const state = get(); if (state.battlePhase !== 'setup' || !(tutorialAllows('OPEN_INVENTORY') || tutorialAllows('PLACE_SUMMON'))) return; const requiredFirst = state.tutorialStepId === 'campaign_place_first' ? state.tutorialContext.firstSummonInstanceId ?? null : null; set({ summonTrayOpen: true, ...(requiredFirst ? { selectedSummonInstanceId: requiredFirst, summonDetailsOpen: false, placementMode: 'idle' as const } : {}) }); emitGameInteraction({ type: 'INVENTORY_OPENED' }); }, closeSummonTray: () => set({ summonTrayOpen: false, summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null }), closeSummonDetails: () => set({ summonDetailsOpen: false, placementMode: 'idle', hoveredBattleCell: null }),
  // Selecting a card during deployment is intentionally a placement gesture, not a
  // details gesture: hide the tray so the entire 4×8 player deployment zone is visible.
  selectSummon: (selectedSummonInstanceId) => { const state = get(); if (state.battlePhase !== 'setup' || !(tutorialAllows('SELECT_SUMMON') || tutorialAllows('PLACE_SUMMON'))) return; const placementSelection = selectedSummonInstanceId !== null && (tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON')); const requiredFirst = state.tutorialStepId === 'campaign_place_first' ? state.tutorialContext.firstSummonInstanceId ?? selectedSummonInstanceId : selectedSummonInstanceId; const placementId = placementSelection ? requiredFirst : selectedSummonInstanceId; set({ selectedSummonInstanceId: placementId, summonTrayOpen: placementSelection ? false : state.summonTrayOpen, summonDetailsOpen: placementSelection ? false : selectedSummonInstanceId !== null, placementMode: placementId === null ? 'idle' : 'selected', hoveredBattleCell: null }); if (selectedSummonInstanceId) emitGameInteraction({ type: 'SUMMON_SELECTED', summonInstanceId: selectedSummonInstanceId }); },
  beginPlacement: (selectedSummonInstanceId) => { const state = get(); if (state.battlePhase !== 'setup' || !(tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON'))) return; const requiredFirst = state.tutorialStepId === 'campaign_place_first' ? state.tutorialContext.firstSummonInstanceId ?? selectedSummonInstanceId : selectedSummonInstanceId; set({ selectedSummonInstanceId: requiredFirst, summonDetailsOpen: true, placementMode: 'selected', hoveredBattleCell: null }); }, beginSummonDrag: (selectedSummonInstanceId) => { const state = get(); if (state.battlePhase !== 'setup' || !tutorialAllows('PLACE_SUMMON')) return; if (state.tutorialStepId === 'campaign_place_first' && selectedSummonInstanceId !== state.tutorialContext.firstSummonInstanceId) return; set({ selectedSummonInstanceId, summonTrayOpen: true, summonDetailsOpen: false, placementMode: 'dragging', hoveredBattleCell: null }); emitGameInteraction({ type: 'SUMMON_DRAG_STARTED', summonInstanceId: selectedSummonInstanceId }); },
  setHoveredBattleCell: (hoveredBattleCell) => set((state) => state.battlePhase !== 'setup' || sameBattleCell(state.hoveredBattleCell, hoveredBattleCell) ? state : { hoveredBattleCell }),
  requestPlacement: (cell) => { const state = get(); if (state.battlePhase !== 'setup' || !(tutorialAllows('PLACE_SUMMON') || tutorialAllows('REPOSITION_SUMMON'))) return; const instanceId = state.selectedSummonInstanceId; if (!instanceId || !canDeploySummon(instanceId, cell, state.placements)) return; const placements = [...state.placements.filter((placement) => placement.summonInstanceId !== instanceId), { summonInstanceId: instanceId, cell }]; set({ placements, boardOccupancy: placements.length, placementMode: 'idle', summonDetailsOpen: false, summonTrayOpen: placements.length === 6 ? false : state.summonTrayOpen, hoveredBattleCell: null }); emitGameInteraction({ type: 'SUMMON_PLACED', summonInstanceId: instanceId }); if (placements.length === 6) emitGameInteraction({ type: 'TEAM_SIZE_6' }); },
  recallSummon: (id) => set((state) => { if (state.battlePhase !== 'setup' || !tutorialAllows('RECALL_SUMMON')) return state; const placements = recallBattlefieldPlacement(id, state.placements); return { placements, boardOccupancy: placements.length, placementMode: 'idle', hoveredBattleCell: null }; }), cancelPlacement: () => { if (get().battlePhase === 'setup') set({ placementMode: 'idle', hoveredBattleCell: null }); },
  initializeBaseCamp: () => { const state = get(); if (state.campPlacements.length > 0) return false; const campPlacements = createInitialCampPlacements(state.inventory, state.placements); if (campPlacements.length !== 6) return false; set({ campPlacements }); return true; },
  selectCampSummon: (selectedCampSummonInstanceId) => { const state = get(); if (selectedCampSummonInstanceId === null) { set({ selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }); return; } if (state.mergePendingIds.includes(selectedCampSummonInstanceId) || !tutorialAllows('SELECT_CAMP_SUMMON') || !getCampPlacementForSummon(selectedCampSummonInstanceId, state.campPlacements)) return; set({ selectedCampSummonInstanceId, campInteractionMode: 'selected', hoveredCampCell: null, mergeError: null }); emitGameInteraction({ type: 'CAMP_SUMMON_SELECTED', summonInstanceId: selectedCampSummonInstanceId }); },
  beginCampDrag: (id) => { const state = get(); if (state.mergePendingIds.includes(id) || !tutorialAllows('SELECT_CAMP_SUMMON') || !getCampPlacementForSummon(id, state.campPlacements)) return; set({ selectedCampSummonInstanceId: id, campInteractionMode: 'dragging', hoveredCampCell: null, mergeError: null }); emitGameInteraction({ type: 'CAMP_SUMMON_SELECTED', summonInstanceId: id }); }, setHoveredCampCell: (hoveredCampCell) => set((state) => state.hoveredCampCell?.x === hoveredCampCell?.x && state.hoveredCampCell?.y === hoveredCampCell?.y ? state : { hoveredCampCell }),
  requestCampMove: (cell) => { const state = get(); const id = state.selectedCampSummonInstanceId; const from = id ? getCampPlacementForSummon(id, state.campPlacements) : undefined; if (!id || !from) return false; const destination = state.campPlacements.find((entry) => entry.cell.x === cell.x && entry.cell.y === cell.y); const target = destination && state.inventory.find((entry) => entry.id === destination.summonInstanceId); const source = state.inventory.find((entry) => entry.id === id); if (target && source) { if (tutorialAllows('MERGE_SUMMONS') && canMerge(source, target)) { void get().requestMerge(id, target.id); return true; } if (tutorialAllows('MERGE_SUMMONS')) { const mergeError = source.definitionId !== target.definitionId || source.tier !== target.tier ? 'Needs same Summon and tier' : 'Max tier reached'; set({ mergeError, campInteractionMode: 'selected', hoveredCampCell: null }); clearMergeFeedback(get, set, mergeError); return false; } }
    // During merging, players can reorganize their camp in either direction:
    // take a protected Summon out to combine it, then put survivors back into
    // open Illuminati slots. Other steps keep their dedicated move restrictions.
    const movingDuringMerge = tutorialAllows('MERGE_SUMMONS');
    if (!tutorialAllows('MOVE_CAMP_SUMMON') && !movingDuringMerge) return false;
    const violatesIlluminatiTutorial = tutorialAllows('MOVE_CAMP_SUMMON') && state.tutorialStepId !== null && (!isIlluminatiCell(cell) || isIlluminatiCell(from.cell));
    if (violatesIlluminatiTutorial || !canPlaceCampSummon(id, cell, state.campPlacements)) { const mergeError = 'That camp cell is unavailable'; set({ mergeError }); clearMergeFeedback(get, set, mergeError); return false; } const campPlacements = moveCampSummon(id, cell, state.campPlacements); const becameFull = !isIlluminatiFull(state.campPlacements) && isIlluminatiFull(campPlacements); set({ campPlacements, selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }); emitGameInteraction({ type: 'CAMP_SUMMON_MOVED', summonInstanceId: id, from: from.cell, to: cell }); if (becameFull) emitGameInteraction({ type: 'ILLUMINATI_FULL' }); return true; },
  requestMerge: async (sourceId, targetId) => { const state = get(); if (!tutorialAllows('MERGE_SUMMONS') || state.mergePendingIds.includes(sourceId) || state.mergePendingIds.includes(targetId)) return false; set({ mergePendingIds: [...state.mergePendingIds, sourceId, targetId], mergeError: null }); const actionId = `tutorial-merge-${state.merge.appliedActionIds.length + 1}-${++mergeActionSequence}`; try { return get().applyMergeResult(await tutorialMergeGateway.mergeSummons({ clientActionId: actionId, sourceSummonInstanceId: sourceId, targetSummonInstanceId: targetId })); } catch (cause) { const mergeError = cause instanceof Error ? cause.message : 'Merge failed. Retry.'; set((current) => ({ mergePendingIds: current.mergePendingIds.filter((id) => id !== sourceId && id !== targetId), mergeError })); clearMergeFeedback(get, set, mergeError); return false; } },
  applyMergeResult: (result) => { const state = get(); if (state.merge.appliedActionIds.includes(result.clientActionId)) return false; const source = state.inventory.find((entry) => entry.id === result.consumedSourceInstanceId); const target = state.inventory.find((entry) => entry.id === result.upgradedTarget.id); if (!source || !target || !getCampPlacementForSummon(source.id, state.campPlacements) || !getCampPlacementForSummon(target.id, state.campPlacements)) return false; const placements = state.placements.map((placement) => placement.summonInstanceId === source.id ? { ...placement, summonInstanceId: target.id } : placement).filter((placement, index, values) => values.findIndex((candidate) => candidate.summonInstanceId === placement.summonInstanceId) === index); const campPlacements = [...state.campPlacements.filter((placement) => placement.summonInstanceId !== source.id && placement.summonInstanceId !== target.id), result.targetPlacement]; const inventory = state.inventory.filter((entry) => entry.id !== source.id && entry.id !== target.id).concat(result.upgradedTarget); const merge = { appliedActionIds: [...state.merge.appliedActionIds, result.clientActionId] }; tutorialMergeGateway.acknowledge(result); set({ inventory, placements, campPlacements, boardOccupancy: placements.length, merge, mergePendingIds: state.mergePendingIds.filter((id) => id !== source.id && id !== target.id), mergeError: null, mergePresentation: result, selectedSummonInstanceId: state.selectedSummonInstanceId === source.id ? target.id : state.selectedSummonInstanceId, selectedCampSummonInstanceId: target.id, campInteractionMode: 'selected', hoveredCampCell: null }); globalThis.setTimeout(() => { if (get().mergePresentation?.clientActionId === result.clientActionId) set({ mergePresentation: null }); }, 850); emitGameInteraction({ type: 'MERGE_COMPLETED', definitionId: target.definitionId, sourceId: source.id, targetId: target.id, fromTier: result.previousTier, toTier: result.nextTier }); return true; },
  cancelCampInteraction: () => set({ selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }), replaceCampPlacements: (campPlacements) => set({ campPlacements, selectedCampSummonInstanceId: null, campInteractionMode: 'idle', hoveredCampCell: null }), reportPerformance: (performance) => set({ performance }), setTutorial: (tutorialStepId, tutorialCompletedStepIds, tutorialContext) => set({ tutorialStepId, tutorialCompletedStepIds, tutorialContext }), restoreSetup: (inventory, placements, campPlacements = [], spawn = createTutorialSpawnRuntime(), merge = { appliedActionIds: [] }, raidDraft = createEmptyRaidSquadDraft(), raidSnapshot: RaidSquadSnapshot | null = null, raidResult: RaidResult | null = null) => { const restoredRaid = sanitizeRaidDraft(raidDraft, inventory); const parsedSnapshot = raidSnapshot ? RaidSquadSnapshotSchema.safeParse(raidSnapshot) : null; const parsedResult = raidResult ? RaidResultSchema.safeParse(raidResult) : null; const snapshotData = parsedSnapshot?.success ? parsedSnapshot.data : null; const acceptedResult = parsedResult?.success && parsedResult.data.clientActionId === snapshotData?.clientActionId ? parsedResult.data : null; const raidError = restoredRaid.error ?? (raidSnapshot && !parsedSnapshot?.success ? 'Locked raid squad was invalid and was cleared.' : null) ?? (raidResult && !acceptedResult ? 'Stored Raid result was invalid and was cleared.' : null); set({ inventory, placements, campPlacements, spawn, merge, raidDraft: restoredRaid.draft, raidFieldPlacements: createEmptyRaidFieldPlacements(), selectedRaidSummonInstanceId: null, hoveredRaidCell: null, raidSnapshot: snapshotData, raidResult: acceptedResult, raidRoundResults: acceptedResult?.rounds ?? [], raidRoundResolutions: [], raidSessionId: acceptedResult?.raidId ?? null, raidRootSeed: acceptedResult?.rootSeed ?? null, raidOpponent: acceptedResult?.opponent ?? null, raidStatus: acceptedResult ? 'complete' : 'setup', raidReplayRoundIndex: 0, raidReplayUnits: {}, raidWinEmitted: Boolean(acceptedResult?.outcome === 'win'), raidError, mergePendingIds: [], mergeError: null, mergePresentation: null, boardOccupancy: placements.length }); },
  openSpawnMachine: () => { const state = get(); if (state.cameraTransitioning || !tutorialAllows('OPEN_SPAWN_MACHINE')) return; set({ spawnOpen: true, spawnError: null }); emitGameInteraction({ type: 'SPAWN_UI_OPENED' }); }, closeSpawnMachine: () => set({ spawnOpen: false, spawnError: null }), setSpawnError: (spawnError) => set({ spawnError }),
  applySpawnRelease: (result) => { const state = get(); if (state.spawn.appliedActionIds.includes(result.clientActionId) || state.inventory.some((entry) => entry.id === result.createdSummon.id)) return false; const campPlacements = [...state.campPlacements, result.destination]; const spawn = { ...state.spawn, balls: result.ballsRemaining, blobProgress: result.blobProgress, tutorialDropIndex: state.spawn.tutorialDropIndex + 1, appliedActionIds: [...state.spawn.appliedActionIds, result.clientActionId] }; set({ inventory: [...state.inventory, result.createdSummon], campPlacements, spawn, spawnError: null }); emitGameInteraction({ type: 'BALL_DROPPED' }); if (campPlacements.length === 36) emitGameInteraction({ type: 'CAMP_FULL' }); return true; },
  openRaidGate: () => { const state = get(); if (state.cameraTransitioning || !tutorialAllows('OPEN_RAID_GATE')) return; set({ scene: 'raid', cameraPresetId: 'raid_overview', cameraTransitioning: true, spawnOpen: false, raidError: null }); emitGameInteraction({ type: 'RAID_GATE_OPENED' }); },
  selectRaidSummon: (roundId, instanceId) => { const state = get(); const currentRound = RAID_ROUND_DEFINITIONS[state.raidRoundResults.length]; if (!currentRound || state.raidStatus !== 'setup' || currentRound.id !== roundId || !tutorialAllows('SELECT_RAID_SUMMON') || !state.inventory.some((item) => item.id === instanceId)) return false; const field = state.raidFieldPlacements[roundId]; if (state.selectedRaidSummonInstanceId === instanceId) { if (field.some((placement) => placement.summonInstanceId === instanceId)) { const placements = field.filter((placement) => placement.summonInstanceId !== instanceId); set({ raidFieldPlacements: { ...state.raidFieldPlacements, [roundId]: placements }, raidDraft: draftForRaidField(state.raidDraft, roundId, placements), selectedRaidSummonInstanceId: null, hoveredRaidCell: null, raidError: null }); return true; } set({ selectedRaidSummonInstanceId: null, hoveredRaidCell: null, raidError: null }); return true; } set({ selectedRaidSummonInstanceId: instanceId, hoveredRaidCell: null, raidError: null }); emitGameInteraction({ type: 'RAID_SUMMON_SELECTED', roundId, summonInstanceId: instanceId }); return true; },
  requestRaidPlacement: (cell) => { const state = get(); const round = RAID_ROUND_DEFINITIONS[state.raidRoundResults.length]; const instanceId = state.selectedRaidSummonInstanceId; if (!round || !instanceId || state.raidStatus !== 'setup' || !tutorialAllows('SELECT_RAID_SUMMON') || !isPlayerDeploymentCell(cell)) return false; const field = state.raidFieldPlacements[round.id]; const withoutSelected = field.filter((placement) => placement.summonInstanceId !== instanceId); if (isBattleCellOccupied(cell, withoutSelected) || withoutSelected.length >= round.slotCount) { set({ raidError: isBattleCellOccupied(cell, withoutSelected) ? 'That field cell is occupied.' : `Deploy ${round.slotCount} Summons before starting.` }); return false; } const placements = [...withoutSelected, { summonInstanceId: instanceId, cell }]; set({ raidFieldPlacements: { ...state.raidFieldPlacements, [round.id]: placements }, raidDraft: draftForRaidField(state.raidDraft, round.id, placements), selectedRaidSummonInstanceId: null, hoveredRaidCell: null, raidError: null }); return true; },
  setHoveredRaidCell: (hoveredRaidCell) => set((state) => state.hoveredRaidCell?.x === hoveredRaidCell?.x && state.hoveredRaidCell?.z === hoveredRaidCell?.z ? state : { hoveredRaidCell }),
  removeRaidSummon: (roundId, slotIndex) => { const state = get(); const currentRound = RAID_ROUND_DEFINITIONS[state.raidRoundResults.length]; if (!currentRound || state.raidStatus !== 'setup' || currentRound.id !== roundId || !tutorialAllows('SELECT_RAID_SUMMON')) return; const removedId = state.raidDraft[roundId][slotIndex]; const placements = removedId ? state.raidFieldPlacements[roundId].filter((placement) => placement.summonInstanceId !== removedId) : state.raidFieldPlacements[roundId]; const result = removeRaidSummon(state.raidDraft, roundId, slotIndex); set({ raidFieldPlacements: { ...state.raidFieldPlacements, [roundId]: placements }, raidDraft: draftForRaidField(result.draft, roundId, placements), selectedRaidSummonInstanceId: state.selectedRaidSummonInstanceId === removedId ? null : state.selectedRaidSummonInstanceId, raidError: result.error }); },
  startRaid: () => { const state = get(); const round = RAID_ROUND_DEFINITIONS[state.raidRoundResults.length]; if (!round || state.raidStatus !== 'setup' || !tutorialAllows('START_RAID')) return false; const locked = finalizeRaidRoundDraft(state.raidDraft, state.inventory, round.id); if (!locked.ok) { set({ raidError: locked.error }); return false; } const attackerPlacements = state.raidFieldPlacements[round.id].map((placement) => ({ summon: locked.squad.find((summon) => summon.instanceId === placement.summonInstanceId)!, cell: placement.cell })); if (attackerPlacements.length !== round.slotCount || new Set(attackerPlacements.map((entry) => entry.cell.x + ':' + entry.cell.z)).size !== attackerPlacements.length) { set({ raidError: 'Place every Summon on a unique player-side cell.' }); return false; } const sessionId = state.raidSessionId ?? `tutorial-raid-${++raidActionSequence}`; const rootSeed = state.raidRootSeed ?? `tutorial-authority:${sessionId}`; const clientActionId = `${sessionId}:${round.id}`; set({ raidStatus: 'resolving', raidError: null, raidSessionId: sessionId, raidRootSeed: rootSeed }); emitGameInteraction({ type: 'RAID_STARTED', clientActionId }); resolveRaidRound(get, set, { clientActionId, raidId: sessionId, rootSeed, contentVersion: GAME_CONTENT_VERSION, roundId: round.id, attacker: locked.squad, attackerPlacements }); return true; },
  retryRaid: () => { const state = get(); if (state.raidStatus === 'error') set({ raidStatus: 'setup', raidError: null }); },
  finishRaidRoundReplay: () => { const state = get(); if (state.raidRoundResults.length < RAID_ROUND_DEFINITIONS.length) { set({ raidStatus: 'setup', raidReplayUnits: {}, selectedRaidSummonInstanceId: null, hoveredRaidCell: null }); return; } const finalSnapshot = finalizeRaidSquadDraft(state.raidDraft, state.inventory, state.raidSessionId ?? `tutorial-raid-${++raidActionSequence}`, GAME_CONTENT_VERSION); const [round1, round2, round3] = state.raidRoundResolutions; if (!finalSnapshot.ok || !state.raidOpponent || !state.raidRootSeed || !state.raidSessionId || !round1 || !round2 || !round3) { set({ raidStatus: 'error', raidError: finalSnapshot.ok ? 'Raid result could not be finalized.' : finalSnapshot.error }); return; } const defender = { contentVersion: GAME_CONTENT_VERSION, round1: round1.defender, round2: round2.defender, round3: round3.defender }; const outcome = resolveRaidOutcome(state.raidRoundResults); const raidResult = RaidResultSchema.parse({ raidId: state.raidSessionId, clientActionId: finalSnapshot.snapshot.clientActionId, contentVersion: GAME_CONTENT_VERSION, rootSeed: state.raidRootSeed, opponent: state.raidOpponent, attacker: { contentVersion: GAME_CONTENT_VERSION, round1: finalSnapshot.snapshot.round1, round2: finalSnapshot.snapshot.round2, round3: finalSnapshot.snapshot.round3 }, defender, rounds: state.raidRoundResults, outcome }); set({ raidSnapshot: finalSnapshot.snapshot, raidResult, raidStatus: 'complete', raidWinEmitted: outcome === 'win', selectedRaidSummonInstanceId: null, hoveredRaidCell: null }); if (outcome === 'win') { emitGameInteraction({ type: 'RAID_WON', raidId: state.raidSessionId }); get().openOpponentCamp(); } },
  openOpponentCamp: () => { const state = get(); if (!state.raidResult || state.raidResult.outcome !== 'win') return; const templates = ['goku','naruto','luffy','eren','l','lelouch']; const summons = templates.map((definitionId, x) => ({ summonInstanceId: `warden-camp:${definitionId}`, definitionId, tier: x === 1 ? 'C' as const : 'F' as const, cell: { x, y: x === 0 ? 0 : 2 }, protected: x === 0, selectableForSteal: x !== 0, pendingSteal: false })); set({ scene: 'opponentCamp', opponentCamp: { raidId: state.raidResult.raidId, opponent: state.raidResult.opponent, summons, claimConsumed: false }, selectedStealTargetId: null, stealResult: null, cameraPresetId: 'base_overview', cameraTransitioning: true }); },
  selectStealTarget: (id) => { const state = get(); const target = state.opponentCamp?.summons.find((entry) => entry.summonInstanceId === id); if (!target) return; if (target.protected) { set({ raidError: 'PROTECTED BY ILLUMINATI' }); return; } if (!target.selectableForSteal || state.opponentCamp?.claimConsumed || !tutorialAllows('SELECT_STEAL')) return; set({ selectedStealTargetId: id, raidError: null }); emitGameInteraction({ type: 'STEAL_TARGET_SELECTED', summonInstanceId: id }); },
  cancelSteal: () => set({ selectedStealTargetId: null }),
  claimSteal: () => { const state = get(); const target = state.opponentCamp?.summons.find((entry) => entry.summonInstanceId === state.selectedStealTargetId); if (!target || !state.opponentCamp || state.opponentCamp.claimConsumed || !tutorialAllows('CONFIRM_STEAL')) return false; const destination = Array.from({ length: 36 }, (_, index) => ({ x: index % 6, y: Math.floor(index / 6) })).find((cell) => !state.campPlacements.some((placement) => placement.cell.x === cell.x && placement.cell.y === cell.y)); if (!destination) { set({ raidError: 'BATTLE CAMP FULL — MAKE SPACE BEFORE CLAIMING' }); return false; } const claimedSummon = { id: target.summonInstanceId, definitionId: target.definitionId, tier: target.tier }; const result: ClaimRaidStealResult = { clientActionId: `tutorial-steal:${state.opponentCamp.raidId}`, raidId: state.opponentCamp.raidId, claimedSummon, destination: { summonInstanceId: claimedSummon.id, cell: destination }, completed: true }; set({ inventory: [...state.inventory, claimedSummon], campPlacements: [...state.campPlacements, result.destination], opponentCamp: { ...state.opponentCamp, claimConsumed: true, summons: state.opponentCamp.summons.filter((entry) => entry.summonInstanceId !== target.summonInstanceId) }, selectedStealTargetId: null, stealResult: result }); emitGameInteraction({ type: 'STEAL_COMPLETED', summonInstanceId: target.summonInstanceId }); globalThis.setTimeout(() => set({ scene: 'base', cameraPresetId: 'base_overview', cameraTransitioning: true }), 700); return true; },
}));

let mergeActionSequence = 0;
let raidActionSequence = 0;
const tutorialMergeGateway = createTutorialMergeGateway(() => { const state = useGameStore.getState(); return { merge: state.merge, inventory: state.inventory, campPlacements: state.campPlacements }; });
function createEmptyRaidFieldPlacements(): Record<RaidRoundId, BattlefieldPlacement[]> { return { round1: [], round2: [], round3: [] }; }
function draftForRaidField(draft: RaidSquadDraft, roundId: RaidRoundId, placements: readonly BattlefieldPlacement[]): RaidSquadDraft { const next = { round1: [...draft.round1], round2: [...draft.round2], round3: [...draft.round3] }; next[roundId] = Array.from({ length: next[roundId].length }, (_, index) => placements[index]?.summonInstanceId ?? null) as RaidSquadDraft[typeof roundId]; return next; }
function resolveRaidRound(get: () => GameState, set: (partial: Partial<GameState>) => void, request: Parameters<typeof tutorialRaidGateway.resolveRound>[0]) {
  void tutorialRaidGateway.resolveRound(request).then((resolution) => {
    const state = get();
    const expected = RAID_ROUND_DEFINITIONS[state.raidRoundResults.length];
    if (!expected || resolution.round.roundId !== expected.id || resolution.raidId !== state.raidSessionId) throw new Error('Raid round response could not be verified. Retry the round.');
    const results = [...state.raidRoundResults, resolution.round];
    set({ raidRoundResults: results, raidRoundResolutions: [...state.raidRoundResolutions, resolution], raidOpponent: resolution.opponent, raidStatus: 'replaying', raidError: null, raidReplayRoundIndex: results.length - 1, raidReplayUnits: {} });
    startRaidRoundReplay(resolution.round, results.length - 1);
  }).catch((cause: unknown) => set({ raidStatus: 'error', raidError: cause instanceof Error ? cause.message : 'Raid round could not be resolved. Retry the round.' }));
}
function clearMergeFeedback(get: () => GameState, set: (partial: Partial<GameState>) => void, message: string) { globalThis.setTimeout(() => { if (get().mergeError === message) set({ mergeError: null }); }, 1800); }

export function getCampCounters(placements: readonly CampPlacement[]) { return { campOccupancy: countCampOccupancy(placements), campCapacity: 36, illuminatiOccupancy: countIlluminatiOccupancy(placements), illuminatiCapacity: 6 }; }
